# docker-compose.yml
version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - nodenet

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks:
      - nodenet
    ports:
      - "3306:3306"

  node:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    command: sh -c "npm install && npm run start"
    tty: true
    depends_on:
      - mysql
    networks:
      - nodenet
    volumes:
      - .:/app

networks:
  nodenet:
    driver: bridge
